# Generated by Django 4.2 on 2023-04-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffCategory',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='category',
            new_name='position',
        ),
    ]
