# Generated by Django 4.2 on 2023-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_type_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lated_minutes',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
